name: GitHub Actions Daily Report Bot

on:
  schedule: # 计划任务触发
    - cron: 34 1 * * * 
    # cron表达式，时区是UTC时间，比我们早8小时，
    

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run
        env:
          SCKEY: ${{ secrets.SCKEY }}
          PWD_KEY: ${{ secrets.PWD_KEY}}
          STUDENT_ID: ${{ secrets.STUDENT_ID}}
          
        run: python main.py
