name: 'GitHub Actions Daily Report Bot'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * 0'

jobs:
  leetcode-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Run'
        env:
          SCKEY: ${{ secrets.SCKEY }}
          STUDENT_ID: ${{ STUDENT_ID}}
          PWD: ${{ PWD}}
        run: python main.py